version: "3.9"
services:
  db:
    image: postgres:15.0-alpine
    container_name: dreamer-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dreamer
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
volumes:
  postgres:
    name: dreamer-db
    driver: local
